### ISSUE TITLE
vim installation error

### ISSUE THREAD

**Issue by akshaygin** [akshay196/get-started#1]
Error log:

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_9wtQRR/ansible_module_dnf.py", line 534, in <module>
    main()
  File "/tmp/ansible_9wtQRR/ansible_module_dnf.py", line 530, in main
    ensure(module, base, params['state'], params['name'], params['autoremove'])
  File "/tmp/ansible_9wtQRR/ansible_module_dnf.py", line 466, in ensure
    base.do_transaction()
  File "/usr/lib/python2.7/site-packages/dnf/base.py", line 591, in do_transaction
    self._trans_error_summary(errstring))
dnf.exceptions.Error: Transaction check error:
  file /usr/share/man/man1/vim.1.gz from install of vim-common-2:8.0.1171-1.fc25.x86_64 conflicts with file from package vim-minimal-2:7.4.1989-2.fc25.x86_64

Error Summary
-------------


fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_9wtQRR/ansible_module_dnf.py\", line 534, in <module>\n    main()\n  File \"/tmp/ansible_9wtQRR/ansible_module_dnf.py\", line 530, in main\n    ensure(module, base, params['state'], params['name'], params['autoremove'])\n  File \"/tmp/ansible_9wtQRR/ansible_module_dnf.py\", line 466, in ensure\n    base.do_transaction()\n  File \"/usr/lib/python2.7/site-packages/dnf/base.py\", line 591, in do_transaction\n    self._trans_error_summary(errstring))\ndnf.exceptions.Error: Transaction check error:\n  file /usr/share/man/man1/vim.1.gz from install of vim-common-2:8.0.1171-1.fc25.x86_64 conflicts with file from package vim-minimal-2:7.4.1989-2.fc25.x86_64\n\nError Summary\n-------------\n\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

```

**Comment by akshaygin** [comment]
It is because `vim-minimal` and `vim-common` ships a copy of man page. However, if we have different versions of `vim-minimal` and `vim-common` then this error occurs. Problem can be solved by updating `vim-minimal` before installing vim.
